apiVersion: v1
kind: Pod
metadata:
  name: soa-payment
  labels:
    app: soa-payment
spec:
  containers:
  - name: soa-payment
    image: huu2412002/soa-payment-service:v01
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 8080
  - name: redis
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 6379