apiVersion: v1
kind: Pod
metadata:
  name: soa-payment
  labels:
    app: soa-payment
spec:
  containers:
  - name: soa-payment
    image: huu2412002/soa-payment-service:v01
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  - name: redis
    image: redis
    resources:
      limits:
        memory: "300Mi"
        cpu: "200m"
    ports:
      - containerPort: 6379