apiVersion: v1
kind: Pod
metadata:
  name: soa-main
  labels:
    app: soa-main
spec:
  containers:
  - name: soa-main
    image: huu2412002/soa-backend:v01
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 8080
  - name: redis
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "100m"
    ports:
      - containerPort: 6379