apiVersion: v1
kind: Service
metadata:
  name: svc-soa-main
spec:
  clusterIP: 10.107.244.72
  selector:
     app: soa-main
  type: ClusterIP
  ports:
    - name: port1
      port: 80
      targetPort: 8080