apiVersion: v1
kind: Service
metadata:
  name: svc-soa-db
spec:
  clusterIP: 10.96.208.40
  selector:
     app: soa-db
  type: ClusterIP
  ports:
    - name: port1
      port: 1433
      targetPort: 1433